# Generated by Django 4.2.5 on 2023-09-20 13:46

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to=server.models.category_icon_upload_path,
            ),
        ),
    ]
