# Generated by Django 4.2.5 on 2023-09-16 22:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0004_server_bannner_server_icon"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="bannner",
            new_name="banner",
        ),
    ]
